name: dartclub_lint
description: Dart analyzer rules, based on pedantic
version: 1.0.0
homepage: https://github.com/dartclub/linter_rules

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  lints: ^2.0.0